<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>fina</artifactId>
        <groupId>net.fina</groupId>
        <version>8.0.3-SNAPSHOT</version>
    </parent>

    <artifactId>fina-first</artifactId>

    <name>fina-first</name>


    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>

        <version.ejb.plugin>2.3</version.ejb.plugin>
    </properties>


    <dependencies>
        <dependency>
            <groupId>net.fina</groupId>
            <artifactId>fina-common</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.fina</groupId>
            <artifactId>fina-ecm</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.fina</groupId>
            <artifactId>fina-bundles</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- Import the CDI API, we use provided scope as the API is included in WildFly -->
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Import the EJB API, we use provided scope as the API is included in WildFly -->
        <dependency>
            <groupId>jakarta.ejb</groupId>
            <artifactId>jakarta.ejb-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.ejb3</groupId>
            <artifactId>jboss-ejb3-ext-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.security.enterprise</groupId>
            <artifactId>jakarta.security.enterprise-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.wildfly.security</groupId>
            <artifactId>wildfly-elytron</artifactId>
            <scope>provided</scope>
        </dependency>

        <!--  jboss-logging API -->
        <dependency>
            <groupId>org.jboss.logging</groupId>
            <artifactId>jboss-logging</artifactId>
            <scope>provided</scope>
        </dependency>

        <!--Apache commons-->
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${version.commons.io}</version>
        </dependency>

        <!--Jackson-->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <!--            <version>${version.jackson}</version>-->
            <scope>provided</scope>
        </dependency>
        <!--        <dependency>-->
        <!--            <groupId>com.fasterxml.jackson.datatype</groupId>-->
        <!--            <artifactId>jackson-datatype-hibernate3</artifactId>-->
        <!--            <version>${version.jackson}</version>-->
        <!--        </dependency>-->
        <!--        <dependency>-->
        <!--            <groupId>com.fasterxml.jackson.datatype</groupId>-->
        <!--            <artifactId>jackson-datatype-hibernate4</artifactId>-->
        <!--            <version>${version.jackson}</version>-->
        <!--        </dependency>-->
        <!--        <dependency>-->
        <!--            <groupId>com.fasterxml.jackson.datatype</groupId>-->
        <!--            <artifactId>jackson-datatype-hibernate5</artifactId>-->
        <!--            <version>${version.jackson}</version>-->
        <!--        </dependency>-->
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-multipart-provider</artifactId>
            <scope>provided</scope>
        </dependency>

        <!--Apache POI-->
        <!--Apache-->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>${version.poi}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>${version.poi}</version>
        </dependency>
        <!--        <dependency>
                    <groupId>org.apache.poi</groupId>
                    <artifactId>poi-ooxml</artifactId>
                    <version>5.2.2</version>
                </dependency>-->

        <!--  <dependency>
              <groupId>org.apache.poi</groupId>
              <artifactId>poi-ooxml-full</artifactId>
              <version>${version.poi}</version>
          </dependency>-->

        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jackson2-provider</artifactId>
            <version>${resteasy.provider.version}</version>
            <scope>test</scope>
        </dependency>

        <!--
            Attention: Be sure nothing pulls in an old dependency with groupId
            "freemarker" (without the "org."), because then you will end up with
            two freemarker.jar-s and unpredictable behavior!
        -->
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>${version.freemarker}</version>
        </dependency>

        <dependency>
            <groupId>org.jboss.msc</groupId>
            <artifactId>jboss-msc</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-clustering-singleton-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.infinispan</groupId>
            <artifactId>infinispan-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- Infinispan -->
<!--        <dependency>-->
<!--            <groupId>org.infinispan</groupId>-->
<!--            <artifactId>infinispan-core</artifactId>-->
<!--&lt;!&ndash;            <version>14.0.13.Final</version>&ndash;&gt;-->
<!--            <scope>provided</scope>-->
<!--        </dependency>-->
        <!-- https://mvnrepository.com/artifact/org.wildfly/wildfly-clustering-service -->
        <dependency>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-clustering-service</artifactId>
            <version>${version.wildfly}</version>
        </dependency>

    </dependencies>

    <build>
        <!-- Specify the artifact name, this is referred to in the EAR's application.xml -->
        <finalName>${project.artifactId}</finalName>
        <!-- Compiler plug-in enforces Java 1.8 compatibility and activates
            annotation processors -->
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <excludes>
                        <exclude>**/ha/**/*.java</exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-ejb-plugin</artifactId>
                <version>${version.ejb.plugin}</version>
                <configuration>
                    <!-- Tell Maven we are using EJB -->
                    <ejbVersion>3.1</ejbVersion>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
