/*===============================================================================================*/
/* Author:                David Chokhonelidze                                                    */
/* DBMS name:             SQLServer up to 2005                                                   */
/* Created on:            09/14/2010                                                             */
/* Revision History       n/a 
 *                        David Chokhonelidze                                                                   */
/* This script is for adding some indexes to increase Return Manager,Schedule Manager performance*/    
/*===============================================================================================*/
/* Script   is for increasing column size in SYS_Strings table            */

alter table SYS_STRINGS alter column VALUE VARCHAR(MAX);
CREATE NONCLUSTERED INDEX [schedule_id_id] ON [dbo].[IN_RETURNS] 
(
    [SCHEDULEID] ASC,
    [ID] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [id] ON [dbo].[IN_BANKS] 
(
    [ID] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [type_id_id] ON [dbo].[IN_RETURN_DEFINITIONS] 
(
    [TYPEID] ASC,
    [ID] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [schedules_1] ON [dbo].[IN_SCHEDULES] 
(
    [PERIODID] ASC,
    [BANKID] ASC,
    [DEFINITIONID] ASC,
    [ID] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [schedules_2] ON [dbo].[IN_SCHEDULES] 
(
    [PERIODID] ASC,
    [DEFINITIONID] ASC,
    [ID] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ret_statuses_1] ON [dbo].[IN_RETURN_STATUSES] 
(
    [RETURNID] ASC,
    [ID] ASC,
    [VERSIONID] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ret_statuses_2] ON [dbo].[IN_RETURN_STATUSES] 
(
    [RETURNID] ASC,
    [VERSIONID] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [user_banks] ON [dbo].[SYS_USER_BANKS] 
(
    [USERID] ASC,
    [BANKID] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_IN_SCHEDULES_7_2021582240__K1_K4_K2] ON [dbo].[IN_SCHEDULES] 
(
	[ID] ASC,
	[PERIODID] ASC,
	[BANKID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX [_dta_index_SYS_STRINGS_7_2034106287__K2_K1_3] ON [dbo].[SYS_STRINGS] 
(
	[LANGID] ASC,
	[ID] ASC
)
INCLUDE ( [VALUE]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX [_dta_index_IN_RETURNS_7_1925581898__K2_K4_K1] ON [dbo].[IN_RETURNS] 
(
	[SCHEDULEID] ASC,
	[VERSIONID] ASC,
	[ID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go



CREATE NONCLUSTERED INDEX [_dta_index_IN_MDT_NODES_7_2018106230__K1_K11_K3_2] ON [dbo].[IN_MDT_NODES] 
(
	[ID] ASC,
	[REQUIRED] ASC,
	[NAMESTRID] ASC
)
INCLUDE ( [CODE]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go



CREATE NONCLUSTERED INDEX [_dta_index_IN_MDT_DEPENDENT_NODES_7_1573580644__K2_K1] ON [dbo].[IN_MDT_DEPENDENT_NODES] 
(
	[DEPENDENTNODEID] ASC,
	[NODEID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go
CREATE NONCLUSTERED INDEX [_dta_index_IN_RETURN_DEFINITIONS_9_1941581955__K1_2] ON [dbo].[IN_RETURN_DEFINITIONS] 
(
    [ID] ASC
)
INCLUDE ( [CODE]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX [_dta_index_IN_BANKS_9_1621580815__K1_2] ON [dbo].[IN_BANKS] 
(
    [ID] ASC
)
INCLUDE ( [CODE]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]






CREATE CLUSTERED INDEX [_dta_index_IN_MDT_DEPENDENT_NODES_c_7_1573580644__K2] ON [dbo].[IN_MDT_DEPENDENT_NODES] 
(
	[DEPENDENTNODEID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
go




