/*
 Database: SQL Server 2012

 Author: Oto Iantbelidze
 E: oto@fina2.net
 Version: 0.1
 Date : 17/03/2016
*/


-- Fi Types
ALTER TABLE IN_BANK_TYPES  
ALTER COLUMN CODE NVARCHAR(50);

-- Fi 
ALTER TABLE IN_BANKS 
ALTER COLUMN CODE NVARCHAR(50);


--Bank Groups 
ALTER TABLE IN_BANK_GROUPS
ALTER COLUMN CODE NVARCHAR(50);

-- License
ALTER TABLE IN_LICENCES
ALTER COLUMN CODE NVARCHAR(50);

--Criterion
ALTER TABLE IN_CRITERION
ALTER COLUMN CODE NVARCHAR(50);

--Region
ALTER TABLE IN_COUNTRY_DATA  
ALTER COLUMN CODE NVARCHAR(50);

-- Definition Tables
ALTER TABLE IN_DEFINITION_TABLES
ALTER COLUMN CODE NVARCHAR(50);

-- Imported Returns
ALTER TABLE IN_IMPORTED_RETURNS
ALTER COLUMN RETURNCODE NVARCHAR(50);

ALTER TABLE IN_IMPORTED_RETURNS
ALTER COLUMN RETURNCODE  NVARCHAR(50);

ALTER TABLE IN_IMPORTED_RETURNS
ALTER COLUMN BANKCODE NVARCHAR(50);

ALTER TABLE IN_IMPORTED_RETURNS
ALTER COLUMN VERSIONCODE NVARCHAR(50);

-- Period Type
ALTER TABLE IN_PERIOD_TYPES
ALTER COLUMN CODE NVARCHAR(50);

-- Return Definitions 
ALTER TABLE IN_RETURN_DEFINITIONS
ALTER COLUMN CODE NVARCHAR(50);

-- Return Types
ALTER TABLE IN_RETURN_TYPES
ALTER COLUMN CODE NVARCHAR(50);

--Return Versions
ALTER TABLE IN_RETURN_VERSIONS
ALTER COLUMN CODE NVARCHAR(50);

ALTER TABLE SYS_UPLOADEDFILE
ALTER COLUMN BANKCODE NVARCHAR(50);

ALTER TABLE IN_MANAGING_BODIES
ALTER COLUMN CODE NVARCHAR(50);

ALTER TABLE IN_MDT_COMPARISON ADD TEMPLATE NVARCHAR(512) NULL;



