/*
 Database: Oracle 11g, 12c

 Author: Oto Iantbelidze
 E: oto@fina2.net
 Version: 0.1
 Date : 17/03/2016
*/


--1 Fi Types
ALTER TABLE IN_BANK_TYPES  
MODIFY (CODE VARCHAR2(50 CHAR) );

--2 Fi 
ALTER TABLE IN_BANKS 
MODIFY (CODE VARCHAR2(50 CHAR) );


--3 Bank Groups 
ALTER TABLE IN_BANK_GROUPS
MODIFY (CODE VARCHAR2(50 CHAR) );

--4 License
ALTER TABLE IN_LICENCES
MODIFY (CODE VARCHAR2(50 CHAR) );

--5 Criterion
ALTER TABLE IN_CRITERION
MODIFY (CODE VARCHAR2(50 CHAR) );

--6 Region
ALTER TABLE IN_COUNTRY_DATA  
MODIFY (CODE NVARCHAR2(50) );

--7 Definition Tables
ALTER TABLE IN_DEFINITION_TABLES
MODIFY (CODE VARCHAR2(50 CHAR) );

--8 Imported Returns
ALTER TABLE IN_IMPORTED_RETURNS
MODIFY (RETURNCODE VARCHAR2(50 CHAR) );

ALTER TABLE IN_IMPORTED_RETURNS
MODIFY (RETURNCODE VARCHAR2(50 CHAR) );

ALTER TABLE IN_IMPORTED_RETURNS
MODIFY (BANKCODE VARCHAR2(50 CHAR) );

ALTER TABLE IN_IMPORTED_RETURNS
MODIFY (VERSIONCODE VARCHAR2(50 CHAR) );

--9 Period Type
ALTER TABLE IN_PERIOD_TYPES
MODIFY (CODE VARCHAR2(50 CHAR) );

--10 Return Definitions 
ALTER TABLE IN_RETURN_DEFINITIONS
MODIFY (CODE VARCHAR2(50 CHAR) );

--11 Return Types
ALTER TABLE IN_RETURN_TYPES
MODIFY (CODE VARCHAR2(50 CHAR) );

--12 Return Versions
ALTER TABLE IN_RETURN_VERSIONS
MODIFY (CODE VARCHAR2(50 CHAR) );

-- 13 SYS_UPLOADED_FILE
ALTER TABLE SYS_UPLOADEDFILE
MODIFY (BANKCODE VARCHAR2(50 CHAR) );

--14 Management
ALTER TABLE IN_MANAGING_BODIES
MODIFY (CODE VARCHAR2(50 CHAR) );

ALTER TABLE IN_MDT_COMPARISON 
ADD (TEMPLATE NVARCHAR2(512) );


