/*
 Database: Oracle 11g, 12c

 Author: Alexander Dolidze
 E: sasha@fina2.net
 Version: 1.1
 Date : 07/07/2016
*/


/*
  Update DB Version
*/
UPDATE sys_properties
SET value = '5.2.9'
WHERE prop_key = 'fina2.database.schemaVersion';

COMMIT;
/*
  To see the output, enable DBMS Output before running this script.
*/
DECLARE 

	--GENERAL PURPOSE PROCEDURES

	--Prints one VARCHAR2 string to console.
	PROCEDURE putLine (line IN VARCHAR2 DEFAULT '')
	IS
	BEGIN
		DBMS_OUTPUT.PUT_LINE(line);
	END;

	--RTRIM the specified VARCHAR2 column of a specified table
	PROCEDURE RTRIMC(tableName IN VARCHAR2, columnName IN VARCHAR2)
	IS
	BEGIN
		putLine('Executing RTRIM on '''||tableName||'''.'''||columnName||'''');
		EXECUTE IMMEDIATE 'UPDATE '||tableName||' SET '||columnName||'=rtrim('||columnName||')';
	END;

BEGIN
	putLine();

	RTRIMC('IN_ABD_AGENTS','ADDRESS');
	RTRIMC('IN_ABD_AGENTS','CODE');
	RTRIMC('IN_ABD_AGENTS','EMAIL');
	RTRIMC('IN_ABD_AGENTS','NAME');
	RTRIMC('IN_ABD_AGENTS','PHONE');
	RTRIMC('IN_ABD_AGENTS_AUD','ADDRESS');
	RTRIMC('IN_ABD_AGENTS_AUD','CODE');
	RTRIMC('IN_ABD_AGENTS_AUD','EMAIL');
	RTRIMC('IN_ABD_AGENTS_AUD','NAME');
	RTRIMC('IN_ABD_AGENTS_AUD','PHONE');
	RTRIMC('IN_ABD_AGENT_STATUSES','NOTE');
	RTRIMC('IN_BANKS','CODE');
	RTRIMC('IN_BANKS','EMAIL');
	RTRIMC('IN_BANKS','FAX');
	RTRIMC('IN_BANKS','PHONE');
	RTRIMC('IN_BANKS','SWIFTCODE');
	RTRIMC('IN_BANKS','TELEX');
	RTRIMC('IN_BANK_BRANCHES','COMMENTSSTRID');
	RTRIMC('IN_BANK_GROUPS','CODE');
	RTRIMC('IN_BANK_MANAGEMENT','PHONE');
	RTRIMC('IN_BANK_TYPES','CODE');
	RTRIMC('IN_BRANCH_MANAGEMENT','PHONE');
	RTRIMC('IN_COUNTRY_DATA_AUD','CODE');
	RTRIMC('IN_CRITERION','CODE');
	RTRIMC('IN_DEFINITION_TABLES','CODE');
	RTRIMC('IN_IMPORTED_RETURNS','BANKCODE');
	RTRIMC('IN_IMPORTED_RETURNS','MESSAGE');
	RTRIMC('IN_IMPORTED_RETURNS','RETURNCODE');
	RTRIMC('IN_IMPORTED_RETURNS','VERSIONCODE');
	RTRIMC('IN_LICENCES','CODE');
	RTRIMC('IN_LICENCES_HISTORY','CHANGE');
	RTRIMC('IN_LICENCE_TYPES','CODE');
	RTRIMC('IN_MAIL_MESSAGE','ADDRESS');
	RTRIMC('IN_MAIL_MESSAGE','FROM_ADDRESS');
	RTRIMC('IN_MAIL_MESSAGE','MAIL_USER');
	RTRIMC('IN_MAIL_MESSAGE','MESSAGE_ID');
	RTRIMC('IN_MAIL_MESSAGE','NOTE');
	RTRIMC('IN_MANAGING_BODIES','CODE');
	RTRIMC('IN_MDT_COMPARISON','EQUATION');
	RTRIMC('IN_MDT_NODES','CODE');
	RTRIMC('IN_PACKAGES','CODE');
	RTRIMC('IN_PACKAGES','NOTE');
	RTRIMC('IN_PERIOD_TYPES','CODE');
	RTRIMC('IN_RETURN_DEFINITIONS','CODE');
	RTRIMC('IN_RETURN_TYPES','CODE');
	RTRIMC('IN_RETURN_VERSIONS','CODE');
	RTRIMC('IN_TASKS','ACTION_PARAMETERS');
	RTRIMC('OUT_MAIL_MESSAGE_REPLY','MAIL_BCC');
	RTRIMC('OUT_MAIL_MESSAGE_REPLY','MAIL_CC');
	RTRIMC('OUT_MAIL_MESSAGE_REPLY','MAIL_CONTENT');
	RTRIMC('OUT_MAIL_MESSAGE_REPLY','MAIL_FROM');
	RTRIMC('OUT_MAIL_MESSAGE_REPLY','MAIL_SENDER');
	RTRIMC('OUT_MAIL_MESSAGE_REPLY','MAIL_TO');
	RTRIMC('OUT_REPORTS','CODE');
	RTRIMC('OUT_REPOSITORY','NAME');
	RTRIMC('OUT_REPOSITORY','SCRIPT');
	RTRIMC('OUT_REPOSITORY_PARAMS','NAME');
	RTRIMC('SYS_ID_GENERATOR','PK_COLUMN_NAME');
	RTRIMC('SYS_LANGUAGES','CODE');
	RTRIMC('SYS_LANGUAGES','DATEFORMAT');
	RTRIMC('SYS_LANGUAGES','FONTFACE');
	RTRIMC('SYS_LANGUAGES','HTMLCHARSET');
	RTRIMC('SYS_LANGUAGES','NAME');
	RTRIMC('SYS_LANGUAGES','NUMBERFORMAT');
	RTRIMC('SYS_LANGUAGES','XMLENCODING');
	RTRIMC('SYS_MENUS','ACTIONKEY');
	RTRIMC('SYS_MENUS','APPLICATION');
	RTRIMC('SYS_PERMISSIONS','IDNAME');
	RTRIMC('SYS_PROPERTIES','PROP_KEY');
	RTRIMC('SYS_PROPERTIES','VALUE');
	RTRIMC('SYS_ROLES','CODE');
	RTRIMC('SYS_STRINGS','VALUE');
	RTRIMC('SYS_UPLOADEDFILE','BANKCODE');
	RTRIMC('SYS_UPLOADEDFILE','FILENAME');
	RTRIMC('SYS_UPLOADEDFILE','REASON');
	RTRIMC('SYS_UPLOADEDFILE','STATUS');
	RTRIMC('SYS_USERS','EMAIL');
	RTRIMC('SYS_USERS','LOGIN');
	RTRIMC('SYS_USERS','PHONE');
	RTRIMC('SYS_USER_STATES','CODE');
	
	putLine('COMMIT');
	COMMIT;
	putLine();
END;