DROP INDEX RETURN_COMPLEX2;
DROP INDEX RETURN_ITEMS_ID;
DROP INDEX RETURN_ITEMS_NODEID;
DROP INDEX RETURN_ITEMS_RETURNID;
DROP INDEX RETURN_ITEMS_ROWNUMBER;
DROP INDEX RETURN_ITEMS_TABLEID;

create index RETURN_COMPEX2 on IN_RETURN_ITEMS (RETURNID,NODEID,VERSIONID,TABLEID,ROWNUMBER)
  tablespace SYSTEM
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    minextents 1
    maxextents unlimited
  );