package net.fina.first.ecm.registry.model;

public enum FiRegistryDocumentType {
    DECREE,
    REPORT_CARD,
    GAP_LETTER,
    REFUSAL_LETTER,
    CONFIRMATION_LETTER,
    REPORT_CARD_LIQUIDATOR,
    LETTER_LIQUIDATOR,
    LETTER_REGISTRY,
    LETTER_HERALD,
    REPORT_CARD_WEBSITE_PUBLISH,
    REPORT_CARD_DOCUMENT_WITHDRAWAL,
    DECREE_CARD_DOCUMENT_WITHDRAWAL,
    REPORT_CARD_REFUSAL,
    DECREE_CARD_REFUSAL,
    REPORT_CARD_BRANCH_REFUSAL,
    CANCELED_BRANCH_REPORT_CARD,
    DECREE_CARD_BRANCH_REFUSAL,
    LETTER_TO_THE_REPRESENTATIVE
}
