package net.fina.first.ecm.fi.model;

public enum AttestationDocumentType {
    ATTESTATION_SHEET,
    ATTESTATION_REJECTION_LETTER,
    ATTESTATION_REJECTION_INTERVIEW_LETTER,
    ATTESTATION_CONFIRMATION_LETTER,
    ATTESTATION_INVITATION_LETTER,
    ATTESTATION_BOARD_DECISION_DRAFT,
    ATTESTATION_IN_QUEUE_CANDIDATES_SHORT,
    ATTESTATION_IN_QUEUE_CANDIDATES_LONG
}
