//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 02:32:15 PM GET 
//


package net.fina.server.fi.xml;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="region" type="{}region"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{}descriptions"/>
 *         &lt;element name="shortname" type="{}descriptions"/>
 *         &lt;element name="address" type="{}descriptions"/>
 *         &lt;element name="comment" type="{}descriptions"/>
 *       &lt;/sequence>
 *       &lt;attribute name="estDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cancelDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "name",
        "shortname",
        "address",
        "chiefAccountant",
        "manager",
        "comment",
})
public class Branch {

    @XmlElement(required = true)
    protected Descriptions name;
    @XmlElement(required = true)
    protected Descriptions shortname;
    @XmlElement(required = true)
    protected Descriptions address;
    @XmlElement(required = false)
    protected Descriptions comment;
    @XmlAttribute(required = true)
    protected String code;
    @XmlAttribute(name = "createDate")
    protected String createDate;
    @XmlAttribute(name = "changeDate")
    protected String changeDate;
    @XmlAttribute(name = "region")
    protected String region;
    @XmlAttribute(name = "disable", required = true)
    protected boolean disable;
    @XmlAttribute(name = "closeDate")
    protected String closeDate;
    @XmlAttribute(name = "suspensionDate")
    protected String suspensionDate;
    @XmlAttribute(name = "renewalDate")
    protected String renewalDate;
    @XmlAttribute(name = "email")
    protected String email;
    @XmlAttribute(name = "phone")
    protected String phone;
    @XmlAttribute(name = "registrationNumber")
    protected String registrationNumber;
    @XmlAttribute(name = "isStorageAvailable")
    protected boolean isStorageAvailable;
    @XmlAttribute(name = "typeCode", required = true)
    protected String typeCode;
    @XmlElement(name = "chiefAccountant")
    protected BranchManager chiefAccountant;
    @XmlElement(name = "manager")
    protected BranchManager manager;

    public Branch() {
    }

    public Branch(String code, Descriptions name, Descriptions shortname, Descriptions address, String region, String createDate, String changeDate, Descriptions comment, Boolean disable) {
        this.code = code;
        this.name = name;
        this.shortname = shortname;
        this.address = address;
        this.region = region;
        this.createDate = createDate;
        this.changeDate = changeDate;
        this.comment = comment;
        this.disable = disable;
    }

    /**
     * Gets the value of the region property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRegion(String value) {
        this.region = value;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setName(Descriptions value) {
        this.name = value;
    }

    /**
     * Gets the value of the shortname property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setShortname(Descriptions value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the address property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setAddress(Descriptions value) {
        this.address = value;
    }

    /**
     * Gets the value of the comment property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setComment(Descriptions value) {
        this.comment = value;
    }

    /**
     * Gets the value of the estDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the estDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCreateDate(String value) {
        this.createDate = value;
    }

    /**
     * Gets the value of the cancelDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getChangeDate() {
        return changeDate;
    }

    /**
     * Sets the value of the cancelDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setChangeDate(String value) {
        this.changeDate = value;
    }

    public boolean isDisable() {
        return disable;
    }

    public void setDisable(boolean disable) {
        this.disable = disable;
    }

    public String getCloseDate() {
        return closeDate;
    }

    public void setCloseDate(String closeDate) {
        this.closeDate = closeDate;
    }

    public String getSuspensionDate() {
        return suspensionDate;
    }

    public void setSuspensionDate(String suspensionDate) {
        this.suspensionDate = suspensionDate;
    }

    public String getRenewalDate() {
        return renewalDate;
    }

    public void setRenewalDate(String renewalDate) {
        this.renewalDate = renewalDate;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getRegistrationNumber() {
        return registrationNumber;
    }

    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    public boolean isStorageAvailable() {
        return isStorageAvailable;
    }

    public void setStorageAvailable(boolean storageAvailable) {
        isStorageAvailable = storageAvailable;
    }

    public String getTypeCode() {
        return typeCode;
    }

    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    public BranchManager getChiefAccountant() {
        return chiefAccountant;
    }

    public void setChiefAccountant(BranchManager chiefAccountant) {
        this.chiefAccountant = chiefAccountant;
    }

    public BranchManager getManager() {
        return manager;
    }

    public void setManager(BranchManager manager) {
        this.manager = manager;
    }
}
