//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 02:32:15 PM GET 
//


package net.fina.server.fi.xml;

import jakarta.xml.bind.annotation.*;

/*
 * fina-fi.xsd schema file location in resources
 * */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "name",
        "shortname",
        "address",
        "groups",
        "licenses",
        "managements",
        "histories",
        "branches",
        "metaInfo",
        "beneficiaries"
})
public class Fi {

    @XmlElement(required = true)
    protected Descriptions name;
    @XmlElement(required = true)
    protected Descriptions shortname;
    @XmlElement(required = true)
    protected Descriptions address;
    @XmlElement(required = true)
    protected Groups groups;
    @XmlElement(required = true)
    protected Licenses licenses;
    @XmlElement(required = true)
    protected Managements managements;
    @XmlElement(required = true)
    protected Histories histories;
    @XmlElement(required = true)
    protected Branches branches;
    @XmlElement(required = true)
    protected LegalPersonMetaInfo metaInfo;
    @XmlElement
    protected Beneficiaries beneficiaries;
    @XmlAttribute(name = "code")
    protected String code;
    @XmlAttribute(name = "overwrite")
    protected Boolean overwrite;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "swift")
    protected String swift;
    @XmlAttribute(name = "phone")
    protected String phone;
    @XmlAttribute(name = "fax")
    protected String fax;
    @XmlAttribute(name = "email")
    protected String email;
    @XmlAttribute(name = "legalForm")
    protected String legalForm;
    @XmlAttribute(name = "identificationCode")
    protected String identificationCode;
    @XmlAttribute(name = "region")
    protected String region;
    @XmlAttribute(name = "contactPerson")
    protected String contactPerson;
    @XmlAttribute(name = "registrationDate")
    protected String registrationDate;
    @XmlAttribute(name = "closeDate")
    protected String closeDate;
    @XmlAttribute(name = "reorganization")
    protected String reorganization;
    @XmlAttribute(name = "representativePerson")
    protected String representativePerson;
    @XmlAttribute(name = "numberOfMobileOffices")
    protected int numberOfMobileOffices;
    @XmlAttribute(name = "numberOfEmploys")
    protected int numberOfEmploys;
    @XmlAttribute(name = "webSite")
    protected String webSite;
    @XmlAttribute(name = "disable")
    protected boolean disable;


    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setName(Descriptions value) {
        this.name = value;
    }

    /**
     * Gets the value of the shortname property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setShortname(Descriptions value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the region property.
     *
     * @return possible object is
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     *
     * @param value allowed object is
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the address property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setAddress(Descriptions value) {
        this.address = value;
    }

    /**
     * Gets the value of the groups property.
     *
     * @return possible object is
     * {@link Groups }
     */
    public Groups getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     *
     * @param value allowed object is
     *              {@link Groups }
     */
    public void setGroups(Groups value) {
        this.groups = value;
    }

    /**
     * Gets the value of the licenses property.
     *
     * @return possible object is
     * {@link Licenses }
     */
    public Licenses getLicenses() {
        return licenses;
    }

    /**
     * Sets the value of the licenses property.
     *
     * @param value allowed object is
     *              {@link Licenses }
     */
    public void setLicenses(Licenses value) {
        this.licenses = value;
    }

    /**
     * Gets the value of the managements property.
     *
     * @return possible object is
     * {@link Managements }
     */
    public Managements getManagements() {
        return managements;
    }

    /**
     * Sets the value of the managements property.
     *
     * @param value allowed object is
     *              {@link Managements }
     */
    public void setManagements(Managements value) {
        this.managements = value;
    }

    /**
     * Gets the value of the histories property.
     *
     * @return possible object is
     * {@link Histories }
     */
    public Histories getHistories() {
        return histories;
    }

    /**
     * Sets the value of the histories property.
     *
     * @param value allowed object is
     *              {@link Histories }
     */
    public void setHistories(Histories value) {
        this.histories = value;
    }

    /**
     * Gets the value of the branches property.
     *
     * @return possible object is
     * {@link Branches }
     */
    public Branches getBranches() {
        return branches;
    }

    /**
     * Sets the value of the branches property.
     *
     * @param value allowed object is
     *              {@link Branches }
     */
    public void setBranches(Branches value) {
        this.branches = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the overwrite property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isOverwrite() {
        return overwrite;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the swift property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSwift() {
        return swift;
    }

    /**
     * Sets the value of the swift property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSwift(String value) {
        this.swift = value;
    }

    /**
     * Gets the value of the phone property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the fax property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the email property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEmail(String value) {
        this.email = value;
    }

    public String getLegalForm() {
        return legalForm;
    }

    public void setLegalForm(String legalForm) {
        this.legalForm = legalForm;
    }

    public String getIdentificationCode() {
        return identificationCode;
    }

    public void setIdentificationCode(String identificationCode) {
        this.identificationCode = identificationCode;
    }

    public Boolean getOverwrite() {
        return overwrite;
    }

    /**
     * Sets the value of the overwrite property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setOverwrite(Boolean value) {
        this.overwrite = value;
    }

    public String getContactPerson() {
        return contactPerson;
    }

    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    public String getRegistrationDate() {
        return registrationDate;
    }

    public void setRegistrationDate(String registrationDate) {
        this.registrationDate = registrationDate;
    }

    public String getCloseDate() {
        return closeDate;
    }

    public void setCloseDate(String closeDate) {
        this.closeDate = closeDate;
    }

    public String getReorganization() {
        return reorganization;
    }

    public void setReorganization(String reorganization) {
        this.reorganization = reorganization;
    }

    public String getRepresentativePerson() {
        return representativePerson;
    }

    public void setRepresentativePerson(String representativePerson) {
        this.representativePerson = representativePerson;
    }

    public int getNumberOfMobileOffices() {
        return numberOfMobileOffices;
    }

    public void setNumberOfMobileOffices(int numberOfMobileOffices) {
        this.numberOfMobileOffices = numberOfMobileOffices;
    }

    public int getNumberOfEmploys() {
        return numberOfEmploys;
    }

    public void setNumberOfEmploys(int numberOfEmploys) {
        this.numberOfEmploys = numberOfEmploys;
    }

    public String getWebSite() {
        return webSite;
    }

    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }

    public boolean isDisable() {
        return disable;
    }

    public void setDisable(boolean disable) {
        this.disable = disable;
    }

    public LegalPersonMetaInfo getMetaInfo() {
        return metaInfo;
    }

    public void setMetaInfo(LegalPersonMetaInfo metaInfo) {
        this.metaInfo = metaInfo;
    }

    public Beneficiaries getBeneficiaries() {
        return beneficiaries;
    }

    public void setBeneficiaries(Beneficiaries beneficiaries) {
        this.beneficiaries = beneficiaries;
    }
}
