//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 02:32:15 PM GET 
//


package net.fina.server.fi.xml;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="first_name" type="{}descriptions"/>
 *         &lt;element name="last_name" type="{}descriptions"/>
 *         &lt;element name="post" type="{}descriptions"/>
 *         &lt;element name="reg_first" type="{}descriptions"/>
 *         &lt;element name="reg_second" type="{}descriptions"/>
 *         &lt;element name="reg_third" type="{}descriptions"/>
 *         &lt;element name="comment_first" type="{}descriptions"/>
 *         &lt;element name="comment_second" type="{}descriptions"/>
 *       &lt;/sequence>
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="phone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="appointmentDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cancelDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "firstName",
        "lastName",
        "post",
        "regFirst",
        "regSecond",
        "regThird",
        "commentFirst",
        "commentSecond",
        "person",
        "managementCommittees",
})
public class Management {

    @XmlElement(name = "first_name", required = true)
    protected Descriptions firstName;
    @XmlElement(name = "last_name", required = true)
    protected Descriptions lastName;
    @XmlElement(required = true)
    protected Descriptions post;
    @XmlElement(name = "reg_first", required = true)
    protected Descriptions regFirst;
    @XmlElement(name = "reg_second", required = true)
    protected Descriptions regSecond;
    @XmlElement(name = "reg_third", required = true)
    protected Descriptions regThird;
    @XmlElement(name = "comment_first", required = true)
    protected Descriptions commentFirst;
    @XmlElement(name = "comment_second", required = true)
    protected Descriptions commentSecond;
    @XmlElement(name = "person")
    protected Person person;
    @XmlElement
    protected ManagementCommittees managementCommittees;
    @XmlAttribute(name = "code")
    protected String code;
    @XmlAttribute(name = "phone")
    protected String phone;
    @XmlAttribute(name = "appointmentDate")
    protected String appointmentDate;
    @XmlAttribute(name = "cancelDate")
    protected String cancelDate;
    @XmlAttribute(name = "dateOfApproval")
    protected String dateOfApproval;
    @XmlAttribute(name = "resident")
    protected boolean resident;
    @XmlAttribute(name = "disable", required = true)
    protected boolean disable;
    @XmlAttribute(name = "position")
    protected String position;
    @XmlAttribute(name = "numberOfReportingEmployees")
    protected int numberOfReportingEmployees;
    @XmlAttribute(name = "mail")
    protected String mail;
    @XmlAttribute(name = "address")
    protected String address;
    @XmlAttribute(name = "portfolio")
    protected String portfolio;
    @XmlAttribute(name = "dependencyStatus")
    protected boolean dependencyStatus;

    public Management() {
    }

    public Management(String code, Descriptions firstName, Descriptions lastName, String phone, String appointmentDate, String cancelDate, Descriptions post, Descriptions regFirst, Descriptions regSecond, Descriptions regThird, Descriptions commentFirst, Descriptions commentSecond, Boolean resident, Boolean disable) {
        this.code = code;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.appointmentDate = appointmentDate;
        this.cancelDate = cancelDate;
        this.post = post;
        this.regFirst = regFirst;
        this.regSecond = regSecond;
        this.regThird = regThird;
        this.commentFirst = commentFirst;
        this.commentSecond = commentSecond;
        this.resident = resident;
        this.disable = disable;
    }

    /**
     * Gets the value of the firstName property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setFirstName(Descriptions value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setLastName(Descriptions value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the post property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getPost() {
        return post;
    }

    /**
     * Sets the value of the post property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setPost(Descriptions value) {
        this.post = value;
    }

    /**
     * Gets the value of the regFirst property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getRegFirst() {
        return regFirst;
    }

    /**
     * Sets the value of the regFirst property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setRegFirst(Descriptions value) {
        this.regFirst = value;
    }

    /**
     * Gets the value of the regSecond property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getRegSecond() {
        return regSecond;
    }

    /**
     * Sets the value of the regSecond property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setRegSecond(Descriptions value) {
        this.regSecond = value;
    }

    /**
     * Gets the value of the regThird property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getRegThird() {
        return regThird;
    }

    /**
     * Sets the value of the regThird property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setRegThird(Descriptions value) {
        this.regThird = value;
    }

    /**
     * Gets the value of the commentFirst property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getCommentFirst() {
        return commentFirst;
    }

    /**
     * Sets the value of the commentFirst property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setCommentFirst(Descriptions value) {
        this.commentFirst = value;
    }

    /**
     * Gets the value of the commentSecond property.
     *
     * @return possible object is
     * {@link Descriptions }
     */
    public Descriptions getCommentSecond() {
        return commentSecond;
    }

    /**
     * Sets the value of the commentSecond property.
     *
     * @param value allowed object is
     *              {@link Descriptions }
     */
    public void setCommentSecond(Descriptions value) {
        this.commentSecond = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the phone property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the appointmentDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAppointmentDate() {
        return appointmentDate;
    }

    /**
     * Sets the value of the appointmentDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAppointmentDate(String value) {
        this.appointmentDate = value;
    }

    /**
     * Gets the value of the cancelDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCancelDate() {
        return cancelDate;
    }

    /**
     * Sets the value of the cancelDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCancelDate(String value) {
        this.cancelDate = value;
    }

    public boolean isResident() {
        return resident;
    }

    public void setResident(boolean resident) {
        this.resident = resident;
    }

    public boolean isDisable() {
        return disable;
    }

    public void setDisable(boolean disable) {
        this.disable = disable;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public int getNumberOfReportingEmployees() {
        return numberOfReportingEmployees;
    }

    public void setNumberOfReportingEmployees(int numberOfReportingEmployees) {
        this.numberOfReportingEmployees = numberOfReportingEmployees;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPortfolio() {
        return portfolio;
    }

    public void setPortfolio(String portfolio) {
        this.portfolio = portfolio;
    }

    public boolean isDependencyStatus() {
        return dependencyStatus;
    }

    public void setDependencyStatus(boolean dependencyStatus) {
        this.dependencyStatus = dependencyStatus;
    }

    public Person getPerson() {
        return person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public ManagementCommittees getManagementCommittees() {
        return managementCommittees;
    }

    public void setManagementCommittees(ManagementCommittees managementCommittees) {
        this.managementCommittees = managementCommittees;
    }

    public String getDateOfApproval() {
        return dateOfApproval;
    }

    public void setDateOfApproval(String dateOfApproval) {
        this.dateOfApproval = dateOfApproval;
    }
}
