//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.16 at 02:32:15 PM GET 
//


package net.fina.server.fi.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="management">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="first_name" type="{}descriptions"/>
 *                   &lt;element name="last_name" type="{}descriptions"/>
 *                   &lt;element name="post" type="{}descriptions"/>
 *                   &lt;element name="reg_first" type="{}descriptions"/>
 *                   &lt;element name="reg_second" type="{}descriptions"/>
 *                   &lt;element name="reg_third" type="{}descriptions"/>
 *                   &lt;element name="comment_first" type="{}descriptions"/>
 *                   &lt;element name="comment_second" type="{}descriptions"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="phone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="appointmentDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="cancelDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "management"
})
public class Managements {

    protected List<Management> management;

    /**
     * Gets the value of the fi property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the management property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManagement().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Management }
     *
     *
     */
    public List<Management> getManagement() {
        if (management == null) {
            management = new ArrayList<Management>();
        }
        return this.management;
    }

}
