/*
 Database: Oracle 11g

 Author: Oto Iantbelidze
 E: oto@fina2.net
 Version: 1.0
 Date : 01/09/2015
*/

update SYS_ID_GENERATOR set value=((select max(id) from IN_PACKAGES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_PACKAGES_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from SYS_AUDIT_LOG)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='SYS_AUDIT_LOG_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_CRITERION)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_CRITERION_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_BANKS)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_BANKS_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_BANK_BRANCHES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_BANK_BRANCHES_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_BANK_MANAGEMENT)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_BANK_MANAGEMENT_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_BANK_TYPES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_BANK_TYPES_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_LICENCES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_LICENSE_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_LICENCE_TYPES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_LICENSE_TYPES_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_MANAGING_BODIES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_MANAGING_BODIES_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_BANK_GROUPS)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_BANK_GROUPS_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from SYS_LANGUAGES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='SYS_LANGUAGE_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_MDT_COMPARISON)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_MDT_COMPARISON_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_MDT_NODES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_MDT_NODES_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_PERIODS)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_PERIODS_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_PERIOD_TYPES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_PERIOD_TYPES_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_COUNTRY_DATA)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_COUNTRY_DATA_MAXID';
update SYS_ID_GENERATOR set value=((select max(REPORTID) from OUT_STORED_REPORTS)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='OUT_REPORTS_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_RETURNS)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_RETURN_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_RETURN_DEFINITIONS)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_DEFINITION_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_RETURN_TYPES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_RETURN_TYPE_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_RETURN_VERSIONS)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_RETURN_VERSION_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_SCHEDULES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_SCHEDULES_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from SYS_PERMISSIONS)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='SYS_PERMISSION_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from SYS_ROLES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='SYS_ROLE_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from SYS_USERS)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='SYS_USER_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from SYS_USER_STATES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='SYS_USER_STATES_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from SYS_UPLOADEDFILE)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='SYS_UPLOADEDFILE_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_IMPORTED_RETURNS)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_IMPORTED_RETURNS_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_RETURN_ITEMS)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_RETURN_ITEM_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from SYS_STRINGS)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='SYS_STRING_MAXID';
update SYS_ID_GENERATOR set value=((select max(id) from IN_RETURN_STATUSES)+1) where SYS_ID_GENERATOR.PK_COLUMN_NAME='IN_RETURN_STATUSES_MAXID';




