package net.fina.server.cems.model;

public enum CEMSSanctionFilterType {
    ORGANIZATION_TYPE,
    NAME,
    ID,
    LICENSE_NUMBER,
    REGISTRATION_LETTER_NUMBER,
    DECISION_MAKING_BODY,
    ACTION_DATE_FROM,
    ACTION_DATE_TO,
    DOCUMENT_NUMBER,
    EXECUTION_PERIOD_FROM,
    EXECUTION_PERIOD_TO,
    INITIAL_APPEAL_DATE_FROM,
    INITIAL_APPEAL_DATE_TO,
    FINAL_APPEAL_DATE_FROM,
    FINAL_APPEAL_DATE_TO,
    STATUS
}
